# Generated by Django 5.2.4 on 2025-08-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=50)),
                ('data_entrega', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
