# Generated by Django 5.2.4 on 2025-08-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimo',
            new_name='agenda',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='data_entrega',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='livro',
            new_name='tarefa',
        ),
    ]
